1:
  title: "Introduction, Tools && Development Environment"
  published: true
  links: 
    "Setup": "https://s3.amazonaws.com/matt-goggin/info2310/INFO2310Setup.html"
    "Agile Manifesto": "http://agilemanifesto.org/"
    "Model-View-Controller": "http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller"
    "Git": "http://git-scm.com"
    "Github": "http://Github.com"
    "Heroku": "http://heroku.com"
    "Ruby": "http://www.ruby-lang.org"
    "Amazon Web Services Console": "https://console.aws.amazon.com/console/home"
    "Hartl Chapter": "http://ruby.railstutorial.org/chapters/beginning#top"

2: 
  title: "Static Pages && Rendering / Ruby"
  published: true
  links:
    "Hartl Chapter on Static Pages": "http://ruby.railstutorial.org/chapters/static-pages"
    "Hartl Chapter on Ruby": "http://ruby.railstutorial.org/chapters/rails-flavored-ruby"
    "Ruby in 20 minutes": "http://www.ruby-lang.org/en/documentation/quickstart/"
    "Understanding Symbols": "http://glu.ttono.us/articles/2005/08/19/understanding-ruby-symbols"
    
3:
  title: "Users && ActiveRecord"
  published: true
  links:
    "Hartl Chapter on modeling users": "http://ruby.railstutorial.org/chapters/modeling-user"
    "Supported Active Record Types": "http://guides.rubyonrails.org/migrations.html#supported-types"
    "Routing in Rails": "http://guides.rubyonrails.org/routing.html"
    "REST": "http://en.wikipedia.org/wiki/Representational_state_transfer"
    "Active Record Callbacks and Validations": "http://guides.rubyonrails.org/active_record_validations_callbacks.html"
    "database.yml examples": "https://gist.github.com/961978"
    "attr_accessor explained": "http://stackoverflow.com/questions/4370960/what-is-attr-accessor-in-ruby"

4:
  title: "Relations && Authenticating Users"
  published: true 
  links:
    "Twitter Bootstrap": "http://twitter.github.com/bootstrap/"
    "Conditional Validation": "http://guides.rubyonrails.org/active_record_validations_callbacks.html#conditional-validation"
    "Asset Pipeline": "http://guides.rubyonrails.org/asset_pipeline.html"
    "Ruby strftime": "http://www.ruby-doc.org/core-1.9.3/Time.html#method-i-strftime"
    
5:
  title: "Signing in && Customizations"
  published: true
  links:
    "Hartl chapter on authentication": "http://ruby.railstutorial.org/chapters/sign-in-sign-out#top"
    "Module Tutorial": "http://www.ruby-doc.org/docs/ProgrammingRuby/html/tut_modules.html"
    "has_secure_password": "http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html"
    "Devise Authentication": "https://github.com/plataformatec/devise"
    "link_to": "http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to"

6:
  title: "Signing out && Access Control && Gems"
  published: true
  links:
    "lecture_6_spec.rb": 'https://raw.github.com/goggin13/curails-mg343/master/spec/requests/lecture_6_spec.rb'
    "faker": "http://faker.rubyforge.org/"

7:
  title: "Pagination && AJAX && Avatars"
  published: true
  links: 
    "lecture_7_spec.rb": "https://raw.github.com/goggin13/curails-mg343/master/spec/requests/lecture_7_spec.rb"
    "will_paginate": "https://github.com/mislav/will_paginate"
    "Ajax in Rails blog entry": "http://blog.madebydna.com/all/code/2011/12/05/ajax-in-rails-3.html"
    "Rails 4": "http://blog.madebydna.com/all/code/2011/12/05/ajax-in-rails-3.html"
    "paperclip": "https://github.com/thoughtbot/paperclip"
    "ImageMagick": "http://www.imagemagick.org/script/index.php"

8:
  title: "Building the feed"
  published: false

9:
  title: "Heroku addons && Stress Testing && Tools"
  published: false

10: 
  title: "TBD"
  published: false

